import { describe, it, expect } from "vitest";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { parseClaudeSessionFile } from "./parser";

/**
 * 写入临时 Claude JSONL 文件并返回其路径。
 */
async function writeTempJsonl(lines: unknown[], filename = `claude-${Date.now()}-${Math.random().toString(16).slice(2)}.jsonl`): Promise<string> {
  const dir = await fs.promises.mkdtemp(path.join(os.tmpdir(), "codexflow-claude-"));
  const fp = path.join(dir, filename);
  const content = lines.map((l) => JSON.stringify(l)).join("\n") + "\n";
  await fs.promises.writeFile(fp, content, "utf8");
  return fp;
}

describe("parseClaudeSessionFile（本地命令 transcript 分类）", () => {
  it("将 Caveat/<command-*>/<local-command-*> 归为 local_command，且不影响 preview 捕获真实首条用户输入", async () => {
    const cwd = "G:\\\\Unity\\\\UnityProject\\\\ALP_Dev";
    const sessionId = "d9b2555d-bf6e-4a26-b78c-a30174e454c1";
    const lines = [
      { type: "file-history-snapshot", snapshot: { timestamp: "2025-12-22T03:22:48.185Z" } },
      {
        cwd,
        sessionId,
        type: "user",
        isMeta: true,
        message: {
          role: "user",
          content:
            "Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.",
        },
      },
      {
        cwd,
        sessionId,
        type: "user",
        message: {
          role: "user",
          content: "<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args></command-args>",
        },
      },
      {
        cwd,
        sessionId,
        type: "user",
        message: {
          role: "user",
          content: "<local-command-stdout>Set model to opus</local-command-stdout>",
        },
      },
      {
        cwd,
        sessionId,
        type: "user",
        message: { role: "user", content: "真实第一条信息：你好" },
      },
    ];

    const fp = await writeTempJsonl(lines, `${sessionId}.jsonl`);
    const stat = await fs.promises.stat(fp);
    const details = await parseClaudeSessionFile(fp, stat, { summaryOnly: false, maxLines: 2000 });

    expect(details.preview).toBe("真实第一条信息：你好");
    expect(details.title).toBe("真实第一条信息：你好");

    const allItems = details.messages.flatMap((m) => (m.content || []).map((c) => ({ role: m.role, ...c })));
    expect(allItems.some((it) => it.type === "local_command")).toBe(true);
    expect(allItems.some((it) => it.type === "input_text" && String(it.text).includes("真实第一条信息"))).toBe(true);
    expect(allItems.some((it) => it.type === "input_text" && String(it.text).includes("Caveat:"))).toBe(false);
  });

  it("summaryOnly 模式下同样应跳过 transcript，并提取后续真实 prompt 作为 preview", async () => {
    const cwd = "G:\\\\Unity\\\\UnityProject\\\\ALP_Dev";
    const sessionId = "d9b2555d-bf6e-4a26-b78c-a30174e454c1";
    const lines = [
      { type: "file-history-snapshot", snapshot: { timestamp: "2025-12-22T03:22:48.185Z" } },
      {
        cwd,
        sessionId,
        type: "user",
        isMeta: true,
        message: { role: "user", content: "Caveat: The messages below were generated by the user while running local commands." },
      },
      {
        cwd,
        sessionId,
        type: "user",
        message: { role: "user", content: "<local-command-stdout>Set model to opus</local-command-stdout>" },
      },
      { cwd, sessionId, type: "user", message: { role: "user", content: "真实首条：OK" } },
    ];

    const fp = await writeTempJsonl(lines, `${sessionId}.ndjson`);
    const stat = await fs.promises.stat(fp);
    const details = await parseClaudeSessionFile(fp, stat, { summaryOnly: true, maxLines: 2000 });

    expect(details.preview).toBe("真实首条：OK");
    expect(details.messages.length).toBe(0);
  });
});

